.TH "/Users/Daniel/PycharmProjects/solar01-master Directory Reference" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Daniel/PycharmProjects/solar01-master Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsolarsystem\fP"
.br
.in -1c
