.TH "/Users/Daniel/PycharmProjects/solar01-master/solarsystem/Planet.py" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Daniel/PycharmProjects/solar01-master/solarsystem/Planet.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsolarsystem\&.Planet\&.Planet\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsolarsystem\&.Planet\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsolarsystem\&.Planet\&.__author__\fP = 'Daniel Herczeg'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
