.TH "solarsystem.start" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.start \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (sc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'Astrid Krickl, Daniel Herczeg'"
.br
.ti -1c
.RI "int \fBwidth\fP = 1000"
.br
.ti -1c
.RI "int \fBheight\fP = 600"
.br
.ti -1c
.RI "tuple \fBs\fP = \fBGalaxie\fP(\fBwidth\fP, \fBheight\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def solarsystem\&.start\&.main ( sc)"

.SH "Variable Documentation"
.PP 
.SS "string solarsystem\&.start\&.__author__ = 'Astrid Krickl, Daniel Herczeg'"

.SS "int solarsystem\&.start\&.height = 600"

.SS "tuple solarsystem\&.start\&.s = \fBGalaxie\fP(\fBwidth\fP, \fBheight\fP)"

.SS "int solarsystem\&.start\&.width = 1000"

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
