.TH "solarsystem.Asteroid.Asteroid" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Asteroid.Asteroid \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsolarsystem\&.Gestirn\&.Gestirn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBposition\fP, dir, \fBspeed\fP, \fBrotSpeed\fP, \fBanim\fP, \fBradius\fP, \fBtextur\fP, \fBdivisions\fP)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBdraw\fP (self, \fBtop\fP, zoom)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBposition\fP"
.br
.ti -1c
.RI "\fBdirection\fP"
.br
.ti -1c
.RI "\fBanim\fP"
.br
.ti -1c
.RI "\fBrotation\fP"
.br
.ti -1c
.RI "\fBrotSpeed\fP"
.br
.ti -1c
.RI "\fBspeed\fP"
.br
.ti -1c
.RI "\fBradius\fP"
.br
.ti -1c
.RI "\fBtextur\fP"
.br
.ti -1c
.RI "\fBdivisions\fP"
.br
.ti -1c
.RI "\fBtop\fP"
.br
.ti -1c
.RI "\fBvalid\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def solarsystem\&.Asteroid\&.Asteroid\&.__init__ ( self,  position,  dir,  speed,  rotSpeed,  anim,  radius,  textur,  divisions)"

.PP
.nf
Konstruktor fuer einen Asteroid
:param position: pos des asteroids
:param dir: richtiung
:param speed: geschwindigkeit
:param rotSpeed: rotationsgeschwindigkeit
:param anim: animation
:param radius: radius
:param textur: textur
:param divisions:
:return:

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def solarsystem\&.Asteroid\&.Asteroid\&.draw ( self,  top,  zoom)"

.PP
.nf
zeichnet einen Asteroiden
:param top:
:param zoom:
:return:

.fi
.PP
 
.SS "def solarsystem\&.Asteroid\&.Asteroid\&.update ( self)"

.PP
.nf
update methode des asteroids
:return:

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "solarsystem\&.Asteroid\&.Asteroid\&.anim"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.direction"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.divisions"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.position"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.radius"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.rotation"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.rotSpeed"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.speed"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.textur"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.top"

.SS "solarsystem\&.Asteroid\&.Asteroid\&.valid"


.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
