.TH "solarsystem.splashscreen" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.splashscreen \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSplash\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
