.TH "solarsystem.Texturen.Texturen" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Texturen.Texturen \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBLoadTexture\fP (pic)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def solarsystem\&.Texturen\&.Texturen\&.LoadTexture ( pic)\fC [static]\fP"

.PP
.nf
ladet eine textur
:param pic: pfad des Bilds der als textur geladen werden soll
:return:

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
