.TH "solarsystem.splashscreen.Splash" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.splashscreen.Splash \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, root, file, wait)"
.br
.ti -1c
.RI "def \fB__enter__\fP (self)"
.br
.ti -1c
.RI "def \fB__exit__\fP (self)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def solarsystem\&.splashscreen\&.Splash\&.__init__ ( self,  root,  file,  wait)"

.PP
.nf
kosntrukotr initialisierng der variablen
:param root: wo das fenster aufgerufen wird
:param file: bild dass angezeigt werden soll
:param wait: wie lange der screen angezeigt werden soll
:return:

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def solarsystem\&.splashscreen\&.Splash\&.__enter__ ( self)"

.PP
.nf
oeffent den splashscreen
:return:

.fi
.PP
 
.SS "def solarsystem\&.splashscreen\&.Splash\&.__exit__ ( self)"

.PP
.nf
schliesst den splashscreen
:return:

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
