.TH "solarsystem.Mond.Mond" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Mond.Mond \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsolarsystem\&.Gestirn\&.Gestirn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBanim\fP, \fBrotation\fP, \fBrotSpeed\fP, parent, \fBentf_rotPoint\fP, \fBmovSpeed\fP, \fBradius\fP, \fBtextur\fP, \fBdivisions\fP)"
.br
.ti -1c
.RI "def \fBupdate\fP (self)"
.br
.ti -1c
.RI "def \fBanimateFaster\fP (self, factor, factorMov)"
.br
.ti -1c
.RI "def \fBanimateSlower\fP (self, factor, factorMov)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBanim\fP"
.br
.ti -1c
.RI "\fBrotation\fP"
.br
.ti -1c
.RI "\fBrotSpeed\fP"
.br
.ti -1c
.RI "\fBrotPoint\fP"
.br
.ti -1c
.RI "\fBposition\fP"
.br
.ti -1c
.RI "\fBentf_rotPoint\fP"
.br
.ti -1c
.RI "\fBmovSpeed\fP"
.br
.ti -1c
.RI "\fBradius\fP"
.br
.ti -1c
.RI "\fBtextur\fP"
.br
.ti -1c
.RI "\fBdivisions\fP"
.br
.ti -1c
.RI "\fBorbitalPos\fP"
.br
.ti -1c
.RI "\fBinialSpeeds\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def solarsystem\&.Mond\&.Mond\&.__init__ ( self,  anim,  rotation,  rotSpeed,  parent,  entf_rotPoint,  movSpeed,  radius,  textur,  divisions)"

.PP
.nf
konstruktir um einen mond zu erstellen
:param anim: animation
:param rotation: roataion
:param rotSpeed: rotationsgeschwindigkeit
:param parent: planet dem der mond gehoert
:param entf_rotPoint: entfernung zum planeten
:param movSpeed: bewegungsgeschw
:param radius: radius
:param textur: textur
:param divisions: unterteilungen
:return:

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def solarsystem\&.Mond\&.Mond\&.animateFaster ( self,  factor,  factorMov)"

.PP
.nf
macht die bewegung schneller
:param factor: geschwindigkeitsfaktor
:param factorMov: bewegungsgeschwindigkeitfaktor
:return:

.fi
.PP
 
.SS "def solarsystem\&.Mond\&.Mond\&.animateSlower ( self,  factor,  factorMov)"

.PP
.nf
macht die animatin langsamer
:param factor: geschwindigkeitsfaktor
:param factorMov: bewegungsgeschwindigkeitfaktor
:return:

.fi
.PP
 
.SS "def solarsystem\&.Mond\&.Mond\&.update ( self)"

.PP
.nf
aktualisiert die animation
:return:

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "solarsystem\&.Mond\&.Mond\&.anim"

.SS "solarsystem\&.Mond\&.Mond\&.divisions"

.SS "solarsystem\&.Mond\&.Mond\&.entf_rotPoint"

.SS "solarsystem\&.Mond\&.Mond\&.inialSpeeds"

.SS "solarsystem\&.Mond\&.Mond\&.movSpeed"

.SS "solarsystem\&.Mond\&.Mond\&.orbitalPos"

.SS "solarsystem\&.Mond\&.Mond\&.position"

.SS "solarsystem\&.Mond\&.Mond\&.radius"

.SS "solarsystem\&.Mond\&.Mond\&.rotation"

.SS "solarsystem\&.Mond\&.Mond\&.rotPoint"

.SS "solarsystem\&.Mond\&.Mond\&.rotSpeed"

.SS "solarsystem\&.Mond\&.Mond\&.textur"


.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
