.TH "solarsystem.Fixstern" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Fixstern \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFixstern\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'Daniel'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string solarsystem\&.Fixstern\&.__author__ = 'Daniel'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
