.TH "solarsystem.Light.Light" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Light.Light \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBposition\fP, \fBcolor\fP)"
.br
.ti -1c
.RI "def \fBinit\fP (self)"
.br
.ti -1c
.RI "def \fBdraw\fP (self)"
.br
.ti -1c
.RI "def \fBdisable\fP (self)"
.br
.ti -1c
.RI "def \fBenable\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenabled\fP"
.br
.ti -1c
.RI "\fBcolor\fP"
.br
.ti -1c
.RI "\fBposition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def solarsystem\&.Light\&.Light\&.__init__ ( self,  position,  color)"

.PP
.nf
Konstruktor für das licht

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def solarsystem\&.Light\&.Light\&.disable ( self)"

.PP
.nf
deaktiviert das licht
:return:

.fi
.PP
 
.SS "def solarsystem\&.Light\&.Light\&.draw ( self)"

.PP
.nf
zeichnet das licht je nach dem ob schatten erwuensch sind
:return:

.fi
.PP
 
.SS "def solarsystem\&.Light\&.Light\&.enable ( self)"

.PP
.nf
aktiviert das licht
:return:

.fi
.PP
 
.SS "def solarsystem\&.Light\&.Light\&.init ( self)"

.PP
.nf
initialisiert das licht

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "solarsystem\&.Light\&.Light\&.color"

.SS "solarsystem\&.Light\&.Light\&.enabled"

.SS "solarsystem\&.Light\&.Light\&.position"


.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
