.TH "solarsystem.Asteroid" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Asteroid \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsteroid\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'Daniel Herczeg'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string solarsystem\&.Asteroid\&.__author__ = 'Daniel Herczeg'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
