.TH "solarsystem.Gestirn" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Gestirn \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGestirn\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'Astrid Krickl, Daniel Herczeg'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string solarsystem\&.Gestirn\&.__author__ = 'Astrid Krickl, Daniel Herczeg'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
