.TH "solarsystem.Texturen" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solarsystem.Texturen \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTexturen\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__author__\fP = 'Astrid Krickl'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string solarsystem\&.Texturen\&.__author__ = 'Astrid Krickl'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
