.TH "/Users/Daniel/PycharmProjects/solar01-master/solarsystem/splashscreen.py" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Daniel/PycharmProjects/solar01-master/solarsystem/splashscreen.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsolarsystem\&.splashscreen\&.Splash\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsolarsystem\&.splashscreen\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
