.TH "/Users/Daniel/PycharmProjects/solar01-master/solarsystem/start.py" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Daniel/PycharmProjects/solar01-master/solarsystem/start.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsolarsystem\&.start\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsolarsystem\&.start\&.main\fP (sc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsolarsystem\&.start\&.__author__\fP = 'Astrid Krickl, Daniel Herczeg'"
.br
.ti -1c
.RI "int \fBsolarsystem\&.start\&.width\fP = 1000"
.br
.ti -1c
.RI "int \fBsolarsystem\&.start\&.height\fP = 600"
.br
.ti -1c
.RI "tuple \fBsolarsystem\&.start\&.s\fP = Galaxie(width, height)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
