.TH "/Users/Daniel/PycharmProjects/solar01-master/solarsystem/Texturen.py" 3 "Thu Apr 16 2015" "Solarsystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Daniel/PycharmProjects/solar01-master/solarsystem/Texturen.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsolarsystem\&.Texturen\&.Texturen\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsolarsystem\&.Texturen\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBsolarsystem\&.Texturen\&.__author__\fP = 'Astrid Krickl'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Solarsystem from the source code\&.
